const header = {
    gotoTopMenu: {
        ko: "상단메뉴 바로가기",
        en: `Shortcuts Top Menu`,
        ja: `上段メニューを開く`,
        chi: `上端菜单快捷键`,
    },
    gotoMainPage: {
        ko: "본문 바로가기",
        en: `Shortcut to main page`,
        ja: `メインページを開く`,
        chi: `直达正文`,
    },
    guidejoin: {
        ko: "가이드 가입하기",
        en: `Subscribe to Guide`,
        ja: `ガイドに登録する`,
        chi: `加入导览`,
    },

    nim: {
        ko: "님",
        en: ``,
        ja: `さん`,
        chi: `先生左右`,
    },
    wellcometxt: {
        ko: "어서오세요",
        en: `Welcome`,
        ja: `いらっしゃいませ`,
        chi: `欢迎光临`,
    },
    itsguide: {
        ko: "It's가이드",
        en: `It'sGuide`,
        ja: `It'sガイド`,
        chi: `It's导游`,
    },
    itstour: {
        ko: "It's투어",
        en: `It'sTour`,
        ja: `It'sツアー`,
        chi: `It's巡游`,
    },
    service: {
        ko: "서비스",
        en: `Service`,
        ja: `サービス`,
        chi: `服务`,
    },
    localFestival: {
        ko: "로컬축제",
        en: `Local festival`,
        ja: `ローカルフェスティバル`,
        chi: `当地庆典`,
    },
    site_info: {
        ko: "소개",
        en: `Introduction`,
        ja: `紹介`,
        chi: `简介质`,
    },
    enter_placeholder: {
        ko: "검색어를 입력해주세요",
        en: `Please enter a search term`,
        ja: `検索キーワードを入力してください`,
        chi: `请输入搜索词`,
    },
    all_menu_title: {
        ko: "전체메뉴",
        en: `All menu`,
        ja: `全メニュー`,
        chi: `全部菜单`,
    },
    point: {
        ko: "포인트",
        en: `Point`,
        ja: `ポイント`,
        chi: `点`,
    },
    won: {
        ko: "원",
        en: `KRW`,
        ja: `ウォン`,
        chi: `元`,
    },
    notification: {
        ko: "알림",
        en: `Notification`,
        ja: `お知らせ`,
        chi: `通知`,
    },
    question: {
        ko: "고객문의",
        en: `Inquiry`,
        ja: `問合せ`,
        chi: `咨询`,
    },
    guideAnnounce: {
        ko: "Guide 공지사항",
        en: `Guide Notice`,
        ja: `Guide お知らせ事項`,
        chi: `Guide 公告事项`,
    },
    announce: {
        ko: "공지사항",
        en: `Notice`,
        ja: `お知らせ事項`,
        chi: `公告事项`,
    },
    event: {
        ko: "이벤트",
        en: `Event`,
        ja: `イベント`,
        chi: `活动`,
    },
    contact_customer_center: {
        ko: "고객센터 문의하기",
        en: `Contact Customer Center`,
        ja: `カスタマーセンターにお問い合わせ`,
        chi: `咨询客服中心`,
    },
    title: {
        ko: "제목",
        en: `Title`,
        ja: `題目`,
        chi: `题目`,
    },
    writer: {
        ko: "작성자",
        en: `Writer`,
        ja: `書き手`,
        chi: `撰文人`,
    },
    date: {
        ko: "날짜",
        en: `Date`,
        ja: `日付`,
        chi: `日期`,
    },

    questions: {
        ko: "문의하기",
        en: `To make an inquiry`,
        ja: `問合せ`,
        chi: `咨询`,
    },
    searchi: {
        ko: "통합검색",
        en: `Integrated Search`,
        ja: `統合検索`,
        chi: `综合搜索`,
    },
    rule: {
        ko: "이용약관",
        en: `Terms and Conditions`,
        ja: `利用規約`,
        chi: `使用条款`,
    },
    privacy_policy: {
        ko: "개인정보처리방침",
        en: `Privacy Policy`,
        ja: `個人情報処理方針`,
        chi: `个人信息处理方针`,
    },
    user_info: {
        ko: "회원정보",
        en: `Member Information`,
        ja: `会員情報`,
        chi: `会员信息`,
    },
    profile_manager: {
        ko: "프로필관리",
        en: `Manage Profiles`,
        ja: `プロフィール管理`,
        chi: `配置管理`,
    },
    review: {
        ko: "리뷰",
        en: `Review`,
        ja: `復習`,
        chi: `检讨`,
    },
    auth: {
        ko: "인증하기",
        en: `Authenticate`,
        ja: `認証`,
        chi: `认证`,
    },
    search: {
        ko: "검색하기",
        en: `Search`,
        ja: `検索`,
        chi: `搜索`,
    },
    fall_review: {
        ko: "리뷰 쓰러가기",
        en: `Fall Review`,
        ja: `レビューを倒す。`,
        chi: `评论倒下`,
    },
    itsguide_recommendationtxt: {
        ko: "잇츠가이드 추천여행",
        en: `It's Guide Recommendation Travel`,
        ja: `おすすめ旅行`,
        chi: `推荐旅行`,
    },
    elimination: {
        ko: "삭제",
        en: `elimination`,
        ja: `削除`,
        chi: `删除`,
    },
    modify: {
        ko: "수정",
        en: `Modify`,
        ja: `修正する`,
        chi: `修改`,
    },
    tomodify: {
        ko: "수정하기",
        en: `To modify`,
        ja: `修正する`,
        chi: `修改`,
    },
    review_manage: {
        ko: "리뷰관리",
        en: `Review Management`,
        ja: `レビュー管理`,
        chi: `评论管理`,
    },
    mypage_write: {
        ko: "나의 게시글",
        en: `My posts`,
        ja: `私の掲示文`,
        chi: `我的帖子`,
    },
    reservation_manager: {
        ko: "예약관리",
        en: `Manage Reservations`,
        ja: `予約管理`,
        chi: `预约管理`,
    },
    mypage_plainning: {
        ko: "나의 It's투어",
        en: `My It's Tour`,
        ja: `僕のIt'sツアー`,
        chi: `我的It's Tour`,
    },
    mypage_settlement: {
        ko: "매출/정산",
        en: `Revenue/Settlement`,
        ja: `売り上げ/精算`,
        chi: `销售/结算`,
    },
    kakaologin: {
        ko: "카카오 로그인",
        en: `Kakao Login`,
        ja: `Kakao Login`,
        chi: `Kakao Login`,
    },
    googlelogin: {
        ko: "구글 로그인",
        en: `Google Login`,
        ja: `Google Login`,
        chi: `Google Login`,
    },
    naverlogin: {
        ko: "네이버 로그인",
        en: `Naver Login`,
        ja: `Naver Login`,
        chi: `Naver Login`,
    },
    login: {
        ko: "로그인",
        en: `Login`,
        ja: `ログイン`,
        chi: `登录`,
    },
    join: {
        ko: "회원가입",
        en: `Join in`,
        ja: `会員加入`,
        chi: `注册会员`,
    },
    id: {
        ko: "아이디",
        en: `ID`,
        ja: `ID`,
        chi: `ID`,
    },
    password: {
        ko: "비밀번호",
        en: `Password`,
        ja: `Password`,
        chi: `Password`,
    },
    keeplogin: {
        ko: "로그인 유지",
        en: `Keep Login`,
        ja: `Keep Login`,
        chi: `Keep Login`,
    },
    rememberid: {
        ko: "아이디 기억",
        en: `Remember ID`,
        ja: `Remember ID`,
        chi: `Remember ID`,
    },
    findmembers: {
        ko: "아이디/비번 찾기",
        en: `Find ID/ password`,
        ja: `IDパスワードを探す`,
        chi: `搜索用户名/密码`,
    },
    guideinfolink: {
        ko: "가이드 정보 자세히보기",
        en: `Guide information`,
        ja: `ガイド情報`,
        chi: `导向信息`,
    },
    productlist: {
        ko: "상품리스트",
        en: `Product list`,
        ja: `商品リスト`,
        chi: `商品清单`,
    },
    moretravels: {
        ko: "판매자의 다른 여행 더보기",
        en: `More Travels`,
        ja: `他の旅行をもっと見る。`,
        chi: `查看更多其他旅行`,
    },
    goodscode: {
        ko: "상품코드",
        en: `Product code`,
        ja: `商品コード`,
        chi: `商品代码`,
    },
    keywords: {
        ko: "키워드",
        en: `Keywords`,
        ja: `キーワード`,
        chi: `关键词`,
    },
    state: {
        ko: "상태",
        en: `State`,
        ja: `状態`,
        chi: `状态`,
    },
    nondisclosure: {
        ko: "비공개",
        en: `Nondisclosure`,
        ja: `非公開`,
        chi: `非公开`,
    },
    public: {
        ko: "공개",
        en: `Public`,
        ja: `状態`,
        chi: `状态`,
    },
    departuredate: {
        ko: "출발일",
        en: `Departure date`,
        ja: `出発日`,
        chi: `出发日期`,
    },
    travelperiod: {
        ko: "여행기간",
        en: `Travel Period`,
        ja: `旅行期間`,
        chi: `旅行期间`,
    },
    itinerary: {
        ko: "여행일정",
        en: `Itinerary`,
        ja: `旅行日程`,
        chi: `旅行日程`,
    },
    like_this: {
        ko: "이런분께 추천드려요.",
        en: `I recommend it to someone like this.`,
        ja: `こんな方にお勧めします`,
        chi: `推荐给以下各位。`,
    },
    guidance_and_notes: {
        ko: "이런분께 추천드려요",
        en: `Recommended for those who like`,
        ja: `こんな方におすすめ致します`,
        chi: `推荐给喜欢的人`,
    },
    participant_preparation: {
        ko: "참가자 준비물",
        en: `Participant Preparation`,
        ja: `参加者準備物`,
        chi: `参赛者准备物品`,
    },
    personnel: {
        ko: "인원",
        en: `Personnel`,
        ja: `人員`,
        chi: `人员`,
    },
    currentnumberofpeople: {
        ko: "현재인원",
        en: `Current number of people`,
        ja: `現在の人員`,
        chi: `现有人员`,
    },
    include: {
        ko: "포함사항",
        en: `Include`,
        ja: `現在の人員`,
        chi: `现有人员`,
    },
    unInclued: {
        ko: "불포함사항",
        en: `Not included`,
        ja: `含まれません`,
        chi: `不包含`,
    },
};

const footer = {
    footer_site_info: {
        ko: "회사소개",
        en: `Company introduction`,
        ja: `会社紹介`,
        chi: `Company introduction`,
    },
    footer_rule: {
        ko: "이용약관",
        en: `Terms of service`,
        ja: `利用規約`,
        chi: `服务条款`,
    },
    footer_privacy_policy: {
        ko: "개인정보처리방침",
        en: `Privacy Policy`,
        ja: `個人情報処理方針`,
        chi: `个人信息处理方针`,
    },
    footer_ceo: {
        ko: "대표",
        en: `CEO`,
        ja: `代表`,
        chi: `代表`,
    },
    footer_busi_num: {
        ko: "사업자등록번호",
        en: `Business license number`,
        ja: `営業鑑札番号`,
        chi: `营业执照号`,
    },
    footer_email: {
        ko: "이메일",
        en: `E-mail`,
        ja: `Eメール`,
        chi: `电邮`,
    },
    businessnumber_check: {
        ko: "사업자정보확인",
        en: `Business number Check`,
        ja: `事業者情報確認`,
        chi: `企业信息确认`,
    },
    itsguide_CEO: {
        ko: "최성희",
        en: "Sung-hee Choi",
        ja: "Sung-hee Choi",
        chi: "Sung-hee Choi",
    },
    case: {
        ko: "건",
        en: "cases",
        ja: "件",
        chi: "件",
    },
    payStatus: {
        ko: "결제상태",
        en: "Payment Status",
        ja: "決済の状態",
        chi: "支付状态",
    },
    productSatus: {
        ko: "상품상태",
        en: "Product Status",
        ja: "상품상태",
        chi: "상품상태",
    },
    noProductData: {
        ko: "아직 등록한 상품이 없습니다.",
        en: "No Regiseted Product yet",
        ja: "まだ登録されて商品がありません。",
        chi: "暂无注册产品。",
    },
    itsguide_adress: {
        ko: "부산광역시 영도구 봉래나루로 33, 306-27",
        en: `(49037)306-27, 33 Bongnaenaru-ro, Yeongdo-gu, Busan, Republic of Korea`,
        ja: `(49037)306-27, 33 Bongnaenaru-ro, Yeongdo-gu, Busan, Republic of Korea`,
        chi: `(49037)306-27, 33 Bongnaenaru-ro, Yeongdo-gu, Busan, Republic of Korea`,
    },
    itsguide_name: {
        ko: "코리아가이드센터(주)",
        en: "코리아가이드센터(주)",
        ja: "코리아가이드센터(주)",
        chi: "코리아가이드센터(주)",
    },
    itsguide_bank: {
        ko: "농협 351-1150-2295-63",
        en: `NH 351-1150-2295-63`,
        ja: `NH 351-1150-2295-63`,
        chi: `NH 351-1150-2295-63`,
    },
    itsguide_FAX: {
        ko: "051-715-0728",
        en: `(+82) 051-715-0728`,
        ja: `(+82) 051-715-0728`,
        chi: `(+82) 051-715-0728`,
    },
    itsguide_phone: {
        ko: "051-715-0727",
        en: `(+82) 051-715-0727`,
        ja: `(+82) 051-715-0727`,
        chi: `(+82) 051-715-0727`,
    },
    footer_businessNumber: {
        ko: "사업자번호",
        en: `Business number`,
        ja: `事業者番号`,
        chi: `营业执照`,
    },
    footer_phoneNumber: {
        ko: "전화번호",
        en: `Phone number`,
        ja: `電話番号`,
        chi: `电话号码`,
    },
    footer_fax: {
        ko: "팩스",
        en: `Fax`,
        ja: `ファックス`,
        chi: `传真`,
    },
    footer_address: {
        ko: "주소",
        en: `Address`,
        ja: `アドレス`,
        chi: `住址`,
    },
    footer_accountNum: {
        ko: "계좌번호",
        en: `Bank account number`,
        ja: `口座番号`,
        chi: `账号`,
    },
    footer_janda: {
        ko: "대한민국 1등 클라우드·핀테크 기반 예약솔루션",
        en: `Korea's No. 1 Cloud and FinTech-based Reservation Solution`,
        ja: `大韓民国1等クラウド·フィンテック基盤予約ソリューション`,
        chi: `大韩民国1等云计算·芬科技基础预约解决方案`,
    },
    guide: {
        ko: "가이드",
        en: "Guide",
        ja: "ガイド",
        chi: "导游",
    },
    master: {
        ko: "마스터",
        en: "Master",
        ja: "マスター",
        chi: "大师",
    },
    anonyFindBooking: {
        ko: "예약조회",
        en: "reservation",
        ja: "予約照会",
        chi: "预订查询",
    },
};

const utils_message = {
    insert_link_plz: {
        ko: "링크 주소를 입력 해주세요.",
        en: `Please enter the link address.`,
        ja: `リンク先のアドレスを入力してください。`,
        chi: `请输入链接地址。`,
    },
    time_over_resv_period: {
        ko: "예약가능 기간이 지났습니다.",
        en: `The reservation period has passed.`,
        ja: `予約可能期間が過ぎました。`,
        chi: `可预约时间已过。`,
    },
    accountHolder: {
        ko: "예금주",
        en: `Account Holder`,
        ja: `預金`,
        chi: `账户持有人`,
    },
    bankName: {
        ko: "은행명",
        en: `Bank Name`,
        ja: `銀行名`,
        chi: `银行名称`,
    },
    unOpend: {
        ko: "비공개",
        en: `closed`,
        ja: `非公開`,
        chi: `非公开`,
    },
    basket_empty_message: {
        ko: "정말로 장바구니 내역을 초기화 하시겠습니까?",
        en: `Are you sure you want to reset your shopping cart history?`,
        ja: `ショッピングカートを初期化しますか？`,
        chi: `确定要初始化购物车吗？`,
    },
    basket_is_empty: {
        ko: "장바구니에 상품이 존재하지 않습니다.",
        en: `Product does not exist in the shopping cart.`,
        ja: `買い物かごには製品がありません。`,
        chi: `购物车上没有产品。`,
    },
    product_info: {
        ko: "상품정보",
        en: `Product Information`,
        ja: `商品情報`,
        chi: `商品情報`,
    },
    option: {
        ko: "옵션",
        en: `Options`,
        ja: `オプション`,
        chi: `期权`,
    },
    product_price: {
        ko: "상품금액",
        en: `Price`,
        ja: `商品金額`,
        chi: `商品金額`,
    },
    status: {
        ko: "상태",
        en: `State`,
        ja: `状態`,
        chi: `状态`,
    },
    startDate: {
        ko: "출발일",
        en: `Departure Date`,
        ja: `出発日`,
        chi: `出发日期`,
    },
    travel_method: {
        ko: "여행방식",
        en: `Travel type`,
        ja: `旅行方式`,
        chi: `旅行方式`,
    },
    startPoint: {
        ko: "출발장소",
        en: `Place of Departure`,
        ja: `出発場所`,
        chi: `出发地点`,
    },
    location: {
        ko: "장소",
        en: `Place`,
        ja: `場所`,
        chi: `场所`,
    },
    party_members: {
        ko: "모집인원",
        en: `Party members`,
        ja: `募集人員`,
        chi: `人员`,
    },
    select_people: {
        ko: "선택인원",
        en: `Number of people`,
        ja: `選択人数`,
        chi: `选择人员`,
    },
    total: {
        ko: "총",
        en: `Total`,
        ja: `合計`,
        chi: `总计`,
    },
    range: {
        ko: "기간",
        en: `Period`,
        ja: `基幹`,
        chi: `期间`,
    },
    one_day: {
        ko: "당일체험",
        en: `Experience`,
        ja: `当日体験`,
        chi: `当日体验`,
    },
    person_unit: {
        ko: "명",
        en: ``,
        ja: `人`,
        chi: `人`,
    },
    change_condition_basket: {
        ko: "조건 추가/변경",
        en: `Add/Change Conditions`,
        ja: `条件の追加変更`,
        chi: `附加条件变更`,
    },
    money_unit: {
        ko: "원",
        en: `won`,
        ja: `won`,
        chi: `won`,
    },
    shopping_cart: {
        ko: "장바구니 담기",
        en: `Shopping carton`,
        ja: `買い物かご入れ`,
        chi: `装菜篮子`,
    },
    end_of_sale: {
        ko: "기간종료",
        en: `End of Sale`,
        ja: `販売終了`,
        chi: `停止销售`,
    },
    travel_details: {
        ko: "여행상세설명",
        en: `Travel Details`,
        ja: `旅行の詳細`,
        chi: `旅行详情说明`,
    },
    make_a_reservation: {
        ko: "예약하기",
        en: `To make a reservation`,
        ja: `予約する`,
        chi: `预约`,
    },
    sum: {
        ko: "총 금액",
        en: `Sum`,
        ja: `合計`,
        chi: `总和`,
    },

    maximum: {
        ko: "최대",
        en: `Maximum`,
        ja: `最大`,
        chi: `最大值`,
    },
    minimum: {
        ko: "최소",
        en: `Minimum`,
        ja: `最小`,
        chi: `最小限度`,
    },
    order: {
        ko: "주문하기",
        en: `Ordering`,
        ja: `注文する`,
        chi: `订购`,
    },
    start_travel: {
        ko: "출발",
        en: `Departure`,
        ja: `出発`,
        chi: `起跑`,
    },
    sum_price: {
        ko: "합계금액",
        en: `Total Amount`,
        ja: `合計金額`,
        chi: `合计金额`,
    },
    adult: {
        ko: "성인",
        en: `Adult`,
        ja: `成人`,
        chi: `成人`,
    },
    kid: {
        ko: "소인",
        en: `Child`,
        ja: `小人`,
        chi: `小人儿`,
    },
    baby: {
        ko: "유아",
        en: `Baby`,
        ja: `幼児`,
        chi: `幼儿`,
    },
    selectAll: {
        ko: "전체선택",
        en: `Select All`,
        ja: `全体選択`,
        chi: `全部选择`,
    },
    selectDelete: {
        ko: "선택삭제",
        en: `Delete`,
        ja: `選択削除`,
        chi: `删除选择`,
    },
    deleteAll: {
        ko: "전체삭제",
        en: `Delete All`,
        ja: `すべて削除`,
        chi: `全部删除`,
    },
    gotoList: {
        ko: "바로가기",
        en: `TO LIST`,
        ja: `立ちくらべ`,
        chi: `快捷键`,
    },
    viewMore: {
        ko: "바로가기",
        en: `Shortcuts`,
        ja: `立ちくらべ`,
        chi: `快捷键`,
    },
    noData: {
        ko: "게시글이 없습니다.",
        en: `There is no post.`,
        ja: `投稿がありません。`,
        chi: `未发表文章。`,
    },
    frequentQuestion: {
        ko: "자주하는 질문",
        en: `Frequently Asked Questions`,
        ja: `よくあるご質問`,
        chi: `常见问题`,
    },
    all: {
        ko: "전체",
        en: `All`,
        ja: `すべて`,
        chi: `全部的`,
    },
    start: {
        ko: "처음",
        en: `First`,
        ja: `初初め`,
        chi: `初初`,
    },
    prev: {
        ko: "이전",
        en: `Prev`,
        ja: `前へ`,
        chi: `以前`,
    },
    next: {
        ko: "다음",
        en: `Next`,
        ja: `次の`,
        chi: `下一个`,
    },
    last: {
        ko: "마지막",
        en: `Last`,
        ja: `しまい`,
        chi: `最后`,
    },
    new: {
        ko: "최신",
        en: `new`,
        ja: `新しい`,
        chi: `新的`,
    },
    announce: {
        ko: "공지사항",
        en: `News`,
        ja: `お知らせ事項`,
        chi: `公告事项`,
    },
    viewCOunt: {
        ko: "조회수",
        en: `view count`,
        ja: `ヒット`,
        chi: `意见`,
    },
    payAmount: {
        ko: "결제금액",
        en: `Pay Amount`,
        ja: `決済金額`,
        chi: `支付金额`,
    },
    payMethod: {
        ko: "결제수단",
        en: `Pay Amount`,
        ja: `決済手段`,
        chi: `付款方式`,
    },
    cardPay: {
        ko: "카드결제",
        en: `Card Pay`,
        ja: `カード決済`,
        chi: `支付信用卡`,
    },
    bankPay: {
        ko: "무통장입금",
        en: `Bank Send`,
        ja: `銀行振込`,
        chi: `银行转帐`,
    },
    bankPayAmt: {
        ko: "입금예정금액",
        en: `Deposit Amount`,
        ja: `入金予定金額`,
        chi: `存款金额`,
    },
    payDate: {
        ko: "결제일",
        en: `Pay Date`,
        ja: `決済`,
        chi: `付款日期`,
    },
    senderName: {
        ko: "입금자명",
        en: `Sender Name`,
        ja: `入金人`,
        chi: `存款人姓名`,
    },
    refundMethod: {
        ko: "환불방법",
        en: `Refund Method`,
        ja: `払い戻し方法`,
        chi: `退款方式`,
    },
    RefundToYourAccount: {
        ko: "환불방법",
        en: `Refund to your account`,
        ja: `払い戻し方法`,
        chi: `退款方式`,
    },
    targetBank: {
        ko: "입금은행",
        en: `Deposit Bank`,
        ja: `入金銀行`,
        chi: `存款银行`,
    },
    senderInfo: {
        ko: "입금자 정보",
        en: `Depositor information`,
        ja: `入金情報`,
        chi: `存款人信息`,
    },
    viewProd: {
        ko: "상품보기",
        en: `View Product`,
        ja: `商品を見る`,
        chi: `查看产品`,
    },
    name: {
        ko: "이름",
        en: `Name`,
        ja: `名前`,
        chi: `名称`,
    },
    contact: {
        ko: "연락처",
        en: `conatact`,
        ja: `連絡先`,
        chi: `接触`,
    },
    buyerNameRequired: {
        ko: "구매자 이름은 필수 입니다",
        en: `Buyer name is required`,
        ja: `バイヤーの名前は必須です`,
        chi: `买家姓名为必填项`,
    },
    buyerContactRequired: {
        ko: "구매자 연락처는 필수 입니다.",
        en: `Buyer contact information is required.`,
        ja: `バイヤー連絡先は必須です。`,
        chi: `需要买家联系信息。`,
    },
    paymentCompleteTop: {
        ko: "예약이 완료 되었습니다.",
        en: `Reservation is complete.`,
        ja: `予約が完了しました。`,
        chi: `预订完成。`,
    },
    ReservationNumber: {
        ko: "예약번호",
        en: `Reservation Number`,
        ja: `予約が完了しました。`,
        chi: `预订完成。`,
    },
    reservationProductName: {
        ko: "예약 상품명",
        en: `Product Name`,
        ja: `商品名`,
        chi: `产品名称`,
    },
    goToHome: {
        ko: "홈으로",
        en: `To Home`,
        ja: `To Home`,
        chi: `To Home`,
    },
    bankExpireMessage: {
        ko: "무통장 입금은 24시간 이내에 입금하지 않으시면 예약이 자동취소 됩니다.",
        en: `If the deposit is not made within 24 hours, the reservation will be automatically canceled.`,
        ja: `振込みは、24時間以内にご入金していアンウシミョン予約が自動的にキャンセルされます。`,
        chi: `如果未在 24 小时内支付押金，预订将自动取消。`,
    },
    checkMyResv: {
        ko: "예약내역 확인하기",
        en: `Check your reservation details`,
        ja: `予約内容を確認する`,
        chi: `检查您的预订详情`,
    },
    resvWillCompleteIf: {
        ko: "입금을 해주시면 예약이 완료됩니다.",
        en: `Reservation is complete upon payment.`,
        ja: `入金をしていただければ予約が完了します。`,
        chi: `付款后预订完成。`,
    },
};

export const info = {
    ...header,
    ...footer,
    ...utils_message,
    // ================= Header파트 END
    // ================= Footer 파트

    // ================= Footer 파트 END
};

//html edit 기능에 의존하지말고  style 오브젝트를 넣으면 안될까?
//style Object를 저장할 공간에 대해서 생각해 보아야할듯
//외국어 오브젝트를 저장할 공간이 필요할듯
//사이트 메뉴를 추가하고 삭제할때 어떻게해야할지 생각해야할듯

export const staticInfo =
    (lang: "ko" | "en" | "ja" | "chi" | "ot") => (key: keyof typeof info) => {
        if (lang === "ot") lang = "en";
        return info[key][lang];
    };

export default info;
