name: Publish Docker image
on:
  push:
    branches: master
jobs:
  work_in_ec2:
    name: Ec2 pull and restart
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: docker pull colton159/docker-nextjs:latest && docker stop pink && docker rm pink && docker run -d -p 80:3000 --name pink colton159/docker-nextjs:latest
