name: Docker Deploy
on:
  push:
    branches: master
jobs:
  pull_in_ec2:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: colton159/docker-nextjs
          tag_with_ref: true
